[build]
  command = "rm -rf package-lock.json node_modules && npm install && npm run build:frontend"
  publish = "frontend/dist/client"

[build.environment]
  VITE_API_URL = "https://auto-shop-pos-backend.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
